'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {SessionStore}=require('../src/store.cjs');const {PetAssets,validateManifest,pngInfo}=require('../src/assets.cjs');
let serial=0;
function event(sessionId,kind,turnId='A',extra={}){return {id:String(++serial),provider:sessionId.split(':')[0],sessionId,kind,turnId,generation:1,sequence:serial,evidence:'host-event',payload:{},...extra};}
test('verified managed completion stays single across duplicate events',()=>{const s=new SessionStore();s.snapshot([{id:'codex:a',provider:'codex',mode:'managed'}]);let notifications=0;s.on('completed',()=>notifications++);s.ingest(event('codex:a','turn.started'));s.ingest(event('codex:a','turn.completed'));s.ingest(event('codex:a','turn.completed'));s.ingest(event('codex:a','turn.started'));assert.equal(s.get('codex:a').state,'done');assert.equal(notifications,1);});
test('late A completion cannot overwrite B or resurrect A',()=>{const s=new SessionStore();s.snapshot([{id:'codex:a',provider:'codex',mode:'managed'}]);s.ingest(event('codex:a','turn.started'));s.ingest(event('codex:a','turn.completed'));s.ingest(event('codex:a','turn.started','B'));s.ingest(event('codex:a','turn.completed','A'));s.ingest(event('codex:a','turn.started','A'));assert.equal(s.get('codex:a').turnId,'B');assert.equal(s.get('codex:a').state,'working');});
test('Claude Stop then tool activity reflects unconfirmed end and continuation',()=>{const s=new SessionStore();let count=0;s.on('completed',()=>count++);s.ingest(event('claude:a','turn.started'));s.ingest(event('claude:a','response.observed','A',{payload:{text:'잠깐 응답'}}));assert.equal(s.get('claude:a').state,'observed');s.ingest(event('claude:a','activity'));assert.equal(s.get('claude:a').state,'working');assert.equal(count,0);});
test('confirmed managed completion survives silence until a new turn starts',()=>{let now=0;const s=new SessionStore({now:()=>now});s.ingest(event('claude:managed','turn.started'));s.patch('claude:managed',{mode:'managed'});s.ingest(event('claude:managed','turn.completed'));assert.equal(s.get('claude:managed').state,'done');now=90001;s.expire();assert.equal(s.get('claude:managed').state,'done');s.ingest(event('claude:managed','turn.started','B'));assert.equal(s.get('claude:managed').state,'working');s.ingest(event('claude:managed','turn.completed','A'));assert.equal(s.get('claude:managed').state,'working');});
test('an unverified completion event remains observed and never emits completion',()=>{const s=new SessionStore();let count=0;s.on('completed',()=>count++);s.ingest(event('claude:observer','turn.started'));s.ingest(event('claude:observer','turn.completed'));assert.equal(s.get('claude:observer').state,'observed');assert.equal(count,0);});
test('parent new turn keeps background child state and child does not change parent',()=>{const s=new SessionStore();s.ingest(event('claude:parent','turn.started','A'));s.ingest(event('claude:child','subagent.started','A',{payload:{parentSessionId:'claude:parent'}}));s.patch('claude:child',{pinned:true});s.ingest(event('claude:parent','turn.started','B'));s.ingest(event('claude:child','activity','A'));assert.equal(s.get('claude:child').pinned,true);assert.equal(s.get('claude:parent').turnId,'B');s.ingest(event('claude:child','response.observed','A'));assert.equal(s.get('claude:parent').state,'working');assert.equal(s.get('claude:child').state,'observed');});
test('missing prompt never asserts completion, stale event becomes unknown, valid activity recovers',()=>{let now=0;const s=new SessionStore({now:()=>now});s.ingest(event('claude:a','response.observed',null));assert.equal(s.get('claude:a').state,'unknown');s.ingest(event('claude:a','turn.started'));now=90001;s.expire();assert.equal(s.get('claude:a').state,'unknown');s.ingest(event('claude:a','activity'));assert.equal(s.get('claude:a').state,'working');});
test('reconnect snapshot does not trigger success and can never grant input capabilities',()=>{const s=new SessionStore();let count=0;s.on('completed',()=>count++);s.snapshot([{id:'codex:a',provider:'codex',state:'done',capabilities:{send:true}}]);assert.equal(s.get('codex:a').state,'unknown');assert.equal(s.get('codex:a').capabilities.send,false);assert.equal(count,0);});
test('failure does not celebrate or resurrect and a new turn can start',()=>{const s=new SessionStore();s.snapshot([{id:'codex:a',provider:'codex',mode:'managed'}]);let count=0;s.on('completed',()=>count++);s.ingest(event('codex:a','turn.started'));s.ingest(event('codex:a','turn.failed'));s.ingest(event('codex:a','turn.started'));assert.equal(s.get('codex:a').state,'error');assert.equal(count,0);s.ingest(event('codex:a','turn.started','B'));assert.equal(s.get('codex:a').state,'working');});
test('old generation cannot overwrite newly connected state',()=>{const s=new SessionStore();s.ingest(event('claude:a','turn.started','B',{generation:2}));s.ingest(event('claude:a','turn.started','A',{generation:1}));assert.equal(s.get('claude:a').turnId,'B');});
test('session resume clears ended flag and freshness works again',()=>{let now=0;const s=new SessionStore({now:()=>now});s.ingest(event('claude:a','turn.started'));s.ingest(event('claude:a','session.ended'));assert.equal(s.get('claude:a').ended,true);s.ingest(event('claude:a','session.started',null));s.ingest(event('claude:a','turn.started','B'));assert.equal(s.get('claude:a').ended,false);assert.equal(s.get('claude:a').state,'working');now=90001;s.expire();assert.equal(s.get('claude:a').state,'unknown');});
test('orphan activity and stop do not assert current turn or observed start',()=>{const s=new SessionStore();s.ingest(event('claude:child','activity','A',{payload:{parentSessionId:'claude:parent'}}));assert.equal(s.get('claude:child').state,'unknown');assert.equal(s.get('claude:child').hasObservedStart,undefined);s.ingest(event('claude:child','response.observed','A'));assert.equal(s.get('claude:child').state,'unknown');s.ingest(event('claude:child','subagent.started','A'));assert.equal(s.get('claude:child').hasObservedStart,true);assert.equal(s.get('claude:child').state,'working');});
test('subagent start without prompt is observed but cannot assert work state',()=>{const s=new SessionStore();s.ingest(event('claude:child','subagent.started',null));assert.equal(s.get('claude:child').hasObservedStart,true);assert.equal(s.get('claude:child').state,'unknown');});
test('frame grid and out of range state are rejected',()=>{const base={version:1,name:'내 펫',columns:3,rows:2,states:{idle:[0],working:[1,2]}};assert.equal(validateManifest(base,{width:1536,height:1024}).columns,3);assert.throws(()=>validateManifest({...base,states:{idle:[6]}},{width:1536,height:1024}));assert.throws(()=>validateManifest(base,{width:100,height:100}));assert.throws(()=>validateManifest({...base,columns:999},{width:1536,height:1024}));});
const pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');
test('custom import copies user image and survives source removal, invalid file keeps prior pet',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pet import '));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const managed=path.join(dir,'managed');const assets=new PetAssets({assetsDir:path.join(dir,'empty'),dataDir:managed});await assets.load();const file=path.join(dir,'새 친구.png');await fs.writeFile(file,pixel);const imported=await assets.import(file);assert.equal(imported.name,'새 친구');await fs.unlink(file);assert.equal((await assets.load()).length,1);assert.equal(assets.catalog[0].id,imported.id);await fs.writeFile(file,'fake');await assert.rejects(()=>assets.import(file));assert.equal(assets.catalog[0].id,imported.id);});
test('manifest rejects traversal, symlink escape and remote URL',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pet path '));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const source=path.join(dir,'source'),managed=path.join(dir,'managed');await fs.mkdir(source);await fs.writeFile(path.join(dir,'outside.png'),pixel);await fs.symlink(path.join(dir,'outside.png'),path.join(source,'link.png'));const a=new PetAssets({assetsDir:dir,dataDir:managed});await a.load();for(const image of ['../outside.png','link.png','https://evil.invalid/x.png']){const f=path.join(source,'friend.pet.json');await fs.writeFile(f,JSON.stringify({version:1,name:'안됨',image,columns:1,rows:1,states:{idle:[0]}}));await assert.rejects(()=>a.import(f));}assert.equal(a.catalog.length,0);});
test('failed copy cannot replace an existing catalog',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'pet rollback '));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const a=new PetAssets({assetsDir:dir,dataDir:path.join(dir,'managed')});await a.load();const f=path.join(dir,'friend.png');await fs.writeFile(f,pixel);const original=await a.import(f);a.dataDir=path.join(dir,'not-a-dir');await fs.writeFile(a.dataDir,'blocking');await fs.writeFile(f,Buffer.concat([pixel,Buffer.from('other')]));await assert.rejects(()=>a.import(f));assert.deepEqual(a.catalog.map(x=>x.id),[original.id]);});
test('oversized PNG dimensions are rejected before decoding',()=>{const buf=Buffer.from(pixel);buf.writeUInt32BE(9000,16);assert.throws(()=>pngInfo(buf));});

test('removed simulation providers cannot restore pets or inject events',()=>{
  const s=new SessionStore();
  s.snapshot([{id:'demo:retired',provider:'demo',pinned:true,state:'done',mode:'managed'},{id:'codex:kept',provider:'codex',pinned:true,petId:'tiger'}]);
  assert.deepEqual(s.list().map(row=>row.id),['codex:kept']);
  assert.equal(s.get('codex:kept').petId,'tiger');
  assert.equal(s.ingest(event('demo:retired','turn.started')),false);
  assert.equal(s.ingest(event('demo:retired','turn.completed')),false);
  assert.equal(s.get('demo:retired'),undefined);
});
